
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 14;
  public static final int FUNCTION = 37;
  public static final int STRING_LITERAL = 2;
  public static final int ASSIGNMENT = 31;
  public static final int EQUALS = 29;
  public static final int DATA_TYPE = 32;
  public static final int OPARENTHESIS = 11;
  public static final int FOR = 33;
  public static final int OBRACKET = 9;
  public static final int NOT = 23;
  public static final int SEMICOLON = 5;
  public static final int AND = 22;
  public static final int CBRACKET = 10;
  public static final int OR = 24;
  public static final int BOOL = 41;
  public static final int DIFFERENT_THAN = 30;
  public static final int COMMA = 7;
  public static final int INC = 20;
  public static final int DIV = 17;
  public static final int IF = 35;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int LESS_OR_EQ = 27;
  public static final int MOD = 19;
  public static final int IMPORT = 39;
  public static final int COLON = 6;
  public static final int ELSE = 36;
  public static final int CPARENTHESIS = 12;
  public static final int WHILE = 34;
  public static final int DECIMAL_LITERAL = 4;
  public static final int SUM = 15;
  public static final int INT_DIV = 18;
  public static final int DEC = 21;
  public static final int MORE_OR_EQ = 28;
  public static final int MORE_THAN = 26;
  public static final int LESS_THAN = 25;
  public static final int SUB = 16;
  public static final int IDENTIFIER = 40;
  public static final int INTEGER_LITERAL = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "DECIMAL_LITERAL",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "DOT",
  "OBRACKET",
  "CBRACKET",
  "OPARENTHESIS",
  "CPARENTHESIS",
  "MUL",
  "POW",
  "SUM",
  "SUB",
  "DIV",
  "INT_DIV",
  "MOD",
  "INC",
  "DEC",
  "AND",
  "NOT",
  "OR",
  "LESS_THAN",
  "MORE_THAN",
  "LESS_OR_EQ",
  "MORE_OR_EQ",
  "EQUALS",
  "DIFFERENT_THAN",
  "ASSIGNMENT",
  "DATA_TYPE",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "FUNCTION",
  "RETURN",
  "IMPORT",
  "IDENTIFIER",
  "BOOL"
  };
}

